// <auto-generated />
namespace back_end.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmedicationsrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmedicationsrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201906241336048_add medications relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
